// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AIGatewayRouteExpansion interface{}

type AIServiceBackendExpansion interface{}

type BackendSecurityPolicyExpansion interface{}

type GatewayConfigExpansion interface{}

type MCPRouteExpansion interface{}

type QuotaPolicyExpansion interface{}
