apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prom-operator-kube-prometh-prometheus.monitoring.svc.cluster.local:9090
    - access: proxy
      name: Prometheus-Legacy
      type: prometheus
      uid: prometheus-legacy
      url: http://prometheus-server.monitoring.svc.cluster.local:80
    - access: proxy
      name: Loki
      type: loki
      url: http://aic-loki.loki.svc.cluster.local:3100
    - access: proxy
      name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.monitoring.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
        serviceMap:
          datasourceUid: prometheus
